-  name: nginx install and run
   hosts: mongodb
   tasks: 
   - name: install nginx
     ansible.builtin.yum:
      name: nginx
      state: insatlled 
   - name: start nginx
     ansible.builtin.service:
      name: nginx
      state: started




   